spring:
  profiles:
    active: dev
  application:
    name: contatos
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:file:./data/database
    username: admin
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
  h2:
    console:
      enabled: false
logging:
  level:
    root: INFO
    com.example.contatos: DEBUG